In [1]:
#!pip install imagekit
#!pip install imgkit
#!pip install weasyprint
!pip freeze

alabaster==0.7.12
anaconda-client==1.7.2
anaconda-navigator==1.8.7
anaconda-project==0.8.2
asn1crypto==0.24.0
astroid==2.2.5
astropy==3.1.2
atomicwrites==1.3.0
attrs==19.1.0
Babel==2.6.0
backcall==0.1.0
backports.os==0.1.1
backports.shutil-get-terminal-size==1.0.0
beautifulsoup4==4.7.1
bitarray==0.8.3
bkcharts==0.2
blaze==0.11.3
bleach==3.1.0
bokeh==1.0.4
boto==2.49.0
Bottleneck==1.2.1
cachetools==3.1.1
cairocffi==1.1.0
CairoSVG==2.4.1
certifi==2019.3.9
cffi==1.12.2
chardet==3.0.4
Click==7.0
cloudpickle==0.8.0
clyent==1.2.2
colorama==0.4.1
comtypes==1.1.7
conda==4.6.14
conda-build==3.10.5
conda-verify==2.0.0
contextlib2==0.5.5
cryptography==2.6.1
cssselect2==0.2.2
cycler==0.10.0
Cython==0.29.6
cytoolz==0.9.0.1
dask==1.1.4
datashape==0.5.4
decorator==4.4.0
defusedxml==0.5.0
distributed==1.26.0
docutils==0.14
entrypoints==0.3
et-xmlfile==1.0.1
fastcache==1.0.2
filelock==3.0.4
Flask==1.0.2
Flask-Cors==3.0.4
gevent==1.4.0
glob2==0.6
google-api-python-client==1.7.11
google-auth==1.6.3
google-auth-httplib2==0.0.3
google-auth-oauthlib==0.4.0
greenlet==0.4.15
h5py==2.9.0
heapdict==1.0.0
html5lib==1.0.1
httplib2==0.13.1
idna==2.8
imageio==2.5.0
imagekit==1.0.6
imagesize==1.1.0
imgkit==1.0.2
importlib-metadata==0.0.0
ipykernel==5.1.0
ipython==7.4.0
ipython-genutils==0.2.0
ipywidgets==7.4.2
isort==4.3.16
itsdangerous==1.1.0
jdcal==1.4
jedi==0.13.3
Jinja2==2.10
jsonschema==3.0.1
jupyter==1.0.0
jupyter-client==5.2.4
jupyter-console==6.0.0
jupyter-core==4.4.0
jupyterlab==0.35.4
jupyterlab-launcher==0.10.5
jupyterlab-server==0.2.0
keyring==18.0.0
kiwisolver==1.0.1
lazy-object-proxy==1.3.1
llvmlite==0.28.0
locket==0.2.0
lxml==4.3.2
MarkupSafe==1.1.1
matplotlib==3.0.3
mccabe==0.6.1
menuinst==1.4.16
mistune==0.8.4
mkl-fft==1.0.10
mkl-random==1.0.2
more-itertools==6.0.0
mpmath==1.1.0
msgpack==0.6.1
multipledispatch==0.6.0
navigator-updater==0.2.1
nbconvert==5.4.1
nbformat==4.4.0
networkx==2.2
nltk==3.4
nose==1.3.7
notebook==5.7.8
numba==0.43.1
numexpr==2.6.9
numpy==1.16.2
numpydoc==0.8.0
oauthlib==3.1.0
odo==0.5.1
olefile==0.46
openpyxl==2.6.1
packaging==19.0
pandas==0.24.2
pandocfilters==1.4.2
parso==0.3.4
partd==0.3.10
path.py==11.5.0
pathlib2==2.3.3
patsy==0.5.1
pdfkit==0.6.1
pep8==1.7.1
pickleshare==0.7.5
Pillow==5.4.1
pkginfo==1.4.2
pluggy==0.9.0
ply==3.11
prometheus-client==0.6.0
prompt-toolkit==2.0.9
psutil==5.6.1
py==1.8.0
pyasn1==0.4.7
pyasn1-modules==0.2.6
pycodestyle==2.5.0
pycosat==0.6.3
pycparser==2.19
pycrypto==2.6.1
pycurl==7.43.0.2
pyflakes==2.1.1
Pygments==2.3.1
pylint==2.3.1
pyodbc==4.0.26
pyOpenSSL==19.0.0
pyparsing==2.3.1
Pyphen==0.9.5
pyreadline==2.1
pyrsistent==0.14.11
PySocks==1.6.8
pytest==4.3.1
pytest-arraydiff==0.3
pytest-astropy==0.5.0
pytest-doctestplus==0.3.0
pytest-openfiles==0.3.2
pytest-remotedata==0.3.1
python-dateutil==2.8.0
pytz==2018.9
PyWavelets==1.0.2
pywin32==223
pywinpty==0.5.5
PyYAML==5.1
pyzmq==18.0.0
QtAwesome==0.5.7
qtconsole==4.4.3
QtPy==1.7.0
reportlab==3.5.23
requests==2.21.0
requests-oauthlib==1.2.0
rope==0.12.0
rsa==4.0
ruamel-yaml==0.15.46
scikit-image==0.14.2
scikit-learn==0.20.3
scipy==1.2.1
seaborn==0.9.0
Send2Trash==1.5.0
simplegeneric==0.8.1
singledispatch==3.4.0.3
six==1.12.0
snowballstemmer==1.2.1
sortedcollections==1.1.2
sortedcontainers==2.1.0
soupsieve==1.8
Sphinx==1.8.5
sphinxcontrib-websupport==1.1.0
spyder==3.3.3
spyder-kernels==0.4.2
SQLAlchemy==1.3.1
statsmodels==0.9.0
sympy==1.3
tables==3.5.1
tblib==1.3.2
terminado==0.8.1
testpath==0.4.2
tinycss2==1.0.2
toolz==0.9.0
tornado==6.0.2
traitlets==4.3.2
typed-ast==1.3.1
typing==3.6.4
unicodecsv==0.14.1
uritemplate==3.0.0
urllib3==1.24.1
wcwidth==0.1.7
WeasyPrint==48
webencodings==0.5.1
Werkzeug==0.14.1
widgetsnbextension==3.4.2
win-inet-pton==1.1.0
win-unicode-console==0.5
wincertstore==0.2
wrapt==1.11.1
xlrd==1.2.0
XlsxWriter==1.1.5
xlwings==0.15.4
xlwt==1.3.0
zict==0.1.4
zipp==0.3.3

In [2]:
import numpy as np
import pandas as pd
import imagekit
import imgkit
import weasyprint

In [3]:
excel_sheet=pd.read_excel('Student Gradebook.xlsx',sheet_name=None,usecols=range(0,10))

In [4]:
len(excel_sheet)

3

In [5]:
data_july=excel_sheet['July'].copy()
data_august=excel_sheet['August'].copy()

In [6]:
data_july.head()

,id,Task,Date,Module,Type,Student,Late Submission,Points,Total,Task Winner
0,1,Linkedin Profile create/update,2019-07-22,Profile Building,"Intent, Creativity,Content",Chandrima,0,6.0,10,0
1,1,Linkedin Profile create/update,2019-07-22,Profile Building,"Intent, Creativity,Content",Dipam,0,7.0,10,0
2,1,Linkedin Profile create/update,2019-07-22,Profile Building,"Intent, Creativity,Content",Durga,0,6.0,10,0
3,1,Linkedin Profile create/update,2019-07-22,Profile Building,"Intent, Creativity,Content",Kaushal,0,7.0,10,0
4,1,Linkedin Profile create/update,2019-07-22,Profile Building,"Intent, Creativity,Content",Arya,0,6.0,10,0

In [7]:
data_july=data_july.dropna(how='all',axis=0)

In [8]:
data_july.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 225 entries, 0 to 224
Data columns (total 10 columns):
id                 225 non-null int64
Task               225 non-null object
Date               225 non-null datetime64[ns]
Module             225 non-null object
Type               225 non-null object
Student            225 non-null object
Late Submission    225 non-null int64
Points             225 non-null float64
Total              225 non-null int64
Task Winner        225 non-null int64
dtypes: datetime64[ns](1), float64(1), int64(4), object(4)
memory usage: 19.3+ KB

In [9]:
data_august.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 911 entries, 0 to 910
Data columns (total 10 columns):
id                 911 non-null int64
Task               911 non-null object
Date               911 non-null object
Module             911 non-null object
Type               911 non-null object
Student            888 non-null object
Late Submission    911 non-null int64
Points             911 non-null float64
Total              911 non-null int64
Task Winner        911 non-null int64
dtypes: float64(1), int64(4), object(5)
memory usage: 71.2+ KB

# Task column

In [10]:
data_july['Task'].value_counts()

AjKyaUkhada                                 69
Ajkyaukhada                                 68
Linkedin Profile create/update              23
Blog on Machine Learning and it's impact    22
Portfolio home page                         22
Blog on Different data based job roles      21
Name: Task, dtype: int64

AjKyaUkhada has two spellings in july data, need to fix it.

In [11]:
data_july.replace('Ajkyaukhada','AjKyaUkhada',inplace=True)

In [12]:
data_july['Task'].value_counts()

AjKyaUkhada                                 137
Linkedin Profile create/update               23
Blog on Machine Learning and it's impact     22
Portfolio home page                          22
Blog on Different data based job roles       21
Name: Task, dtype: int64

In [13]:
data_august['Task'].value_counts()

AjKyaUkhada                      692
Knowledge Sharing                103
Blog and Project Pages            21
PPT Submission                    20
Online Resume                     20
Blog on Data Analysis Process     19
Video Resume                      18
Github Profile Creation           18
Name: Task, dtype: int64

# Date columns

In [14]:
data_july.head()

,id,Task,Date,Module,Type,Student,Late Submission,Points,Total,Task Winner
0,1,Linkedin Profile create/update,2019-07-22,Profile Building,"Intent, Creativity,Content",Chandrima,0,6.0,10,0
1,1,Linkedin Profile create/update,2019-07-22,Profile Building,"Intent, Creativity,Content",Dipam,0,7.0,10,0
2,1,Linkedin Profile create/update,2019-07-22,Profile Building,"Intent, Creativity,Content",Durga,0,6.0,10,0
3,1,Linkedin Profile create/update,2019-07-22,Profile Building,"Intent, Creativity,Content",Kaushal,0,7.0,10,0
4,1,Linkedin Profile create/update,2019-07-22,Profile Building,"Intent, Creativity,Content",Arya,0,6.0,10,0

In [15]:
data_july.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 225 entries, 0 to 224
Data columns (total 10 columns):
id                 225 non-null int64
Task               225 non-null object
Date               225 non-null datetime64[ns]
Module             225 non-null object
Type               225 non-null object
Student            225 non-null object
Late Submission    225 non-null int64
Points             225 non-null float64
Total              225 non-null int64
Task Winner        225 non-null int64
dtypes: datetime64[ns](1), float64(1), int64(4), object(4)
memory usage: 19.3+ KB

In [16]:
data_august.head()

,id,Task,Date,Module,Type,Student,Late Submission,Points,Total,Task Winner
0,0,AjKyaUkhada,2019-08-01 13:26:57,Ritual,Consistency,Sonali,0,2.0,2,0
1,0,AjKyaUkhada,2019-08-01 14:40:42,Ritual,Consistency,Chandrima,0,2.0,2,0
2,0,AjKyaUkhada,2019-08-01 14:44:34,Ritual,Consistency,Purbita,0,2.0,2,0
3,0,AjKyaUkhada,2019-08-01 14:47:05,Ritual,Consistency,Kunal,0,2.0,2,0
4,0,AjKyaUkhada,2019-08-01 14:48:11,Ritual,Consistency,Kaushal,0,2.0,2,0

In [17]:
data_august.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 911 entries, 0 to 910
Data columns (total 10 columns):
id                 911 non-null int64
Task               911 non-null object
Date               911 non-null object
Module             911 non-null object
Type               911 non-null object
Student            888 non-null object
Late Submission    911 non-null int64
Points             911 non-null float64
Total              911 non-null int64
Task Winner        911 non-null int64
dtypes: float64(1), int64(4), object(5)
memory usage: 71.2+ KB

July has date time dtype but august doesn't, let's fix it.

In [18]:
data_july['Date']=pd.to_datetime(data_july['Date'],errors='ignore')

In [19]:
data_august['Date']=pd.to_datetime(data_august['Date'],errors='ignore')

# Module Column

In [20]:
data_july['Module'].value_counts()

Ritual                          137
Profile Building                 45
Introduction to Data Science     43
Name: Module, dtype: int64

In [21]:
data_august['Module'].value_counts()

Ritual              795
Profile Building     77
Machine Learning     20
Data Analytics       19
Name: Module, dtype: int64

No problem with module column, also no null values

# Type column

In [22]:
data_july['Type'].value_counts()

Consistency                                                 137
Knowledge,Understanding,Communication,Analytical Ability     43
Intent, Creativity,Content                                   23
sincerity,Creativity,Design-sense,Writing                    22
Name: Type, dtype: int64

In [23]:
data_august['Type'].value_counts()

Consistency                                   692
Consistency,Curiosity                         103
Creativity, Intent                             21
Diligence                                      20
Creativity,Intent,sincerity                    20
Analysis, communication, sincerity             19
Sincerity,Hard-work                            18
Creativity,Communication,Intent,Confidence     18
Name: Type, dtype: int64

No problem in type column, nothing so to understand

# Student column

We know from above info(), data_august has some null values, let's see to it

In [24]:
data_august[data_august['Student'].isnull()]

,id,Task,Date,Module,Type,Student,Late Submission,Points,Total,Task Winner
108,0,AjKyaUkhada,2019-08-04 02:52:50,Ritual,Consistency,NaN,0,2.0,2,0
124,0,AjKyaUkhada,2019-08-05 04:17:09,Ritual,Consistency,NaN,0,2.0,2,0
127,0,AjKyaUkhada,2019-08-05 15:47:07,Ritual,Consistency,NaN,0,2.0,2,0
147,0,AjKyaUkhada,2019-08-06 16:13:29,Ritual,Consistency,NaN,0,2.0,2,0
178,0,AjKyaUkhada,2019-08-08 00:53:47,Ritual,Consistency,NaN,0,2.0,2,0
182,0,AjKyaUkhada,2019-08-08 15:49:56,Ritual,Consistency,NaN,0,2.0,2,0
222,0,AjKyaUkhada,2019-08-10 04:11:39,Ritual,Consistency,NaN,0,2.0,2,0
233,0,AjKyaUkhada,2019-08-10 17:19:44,Ritual,Consistency,NaN,0,2.0,2,0
246,0,Knowledge Sharing,2019-08-11 02:17:18,Ritual,"Consistency,Curiosity",NaN,0,2.0,2,0
429,0,AjKyaUkhada,2019-08-20 16:36:08,Ritual,Consistency,NaN,0,2.0,2,0
454,0,AjKyaUkhada,2019-08-16 02:29:20,Ritual,Consistency,NaN,0,2.0,2,0
482,0,AjKyaUkhada,2019-08-17 16:52:55,Ritual,Consistency,NaN,0,2.0,2,0
505,0,AjKyaUkhada,2019-08-16 02:30:28,Ritual,Consistency,NaN,0,2.0,2,0
527,0,AjKyaUkhada,2019-08-16 02:33:33,Ritual,Consistency,NaN,0,2.0,2,0
703,0,AjKyaUkhada,2019-08-31 14:33:42,Ritual,Consistency,NaN,0,2.0,2,0
718,0,AjKyaUkhada,2019-09-01 04:23:21,Ritual,Consistency,NaN,0,2.0,2,0
773,0,AjKyaUkhada,2019-09-03 16:18:05,Ritual,Consistency,NaN,0,2.0,2,0
797,0,AjKyaUkhada,2019-09-04 17:13:39,Ritual,Consistency,NaN,0,2.0,2,0
823,0,AjKyaUkhada,2019-09-06 03:21:22,Ritual,Consistency,NaN,0,2.0,2,0
838,0,AjKyaUkhada,2019-09-06 18:00:36,Ritual,Consistency,NaN,0,2.0,2,0
872,0,AjKyaUkhada,2019-09-08 16:14:06,Ritual,Consistency,NaN,0,2.0,2,0
873,0,AjKyaUkhada,2019-09-08 16:15:16,Ritual,Consistency,NaN,0,2.0,2,0
899,0,AjKyaUkhada,2019-09-09 17:38:42,Ritual,Consistency,NaN,0,2.0,2,0

Since, there is no way to correctly fill this data, we are just gonna drop those rows.

In [25]:
data_august.dropna(subset=['Student'],inplace=True)

In [26]:
data_august.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 888 entries, 0 to 910
Data columns (total 10 columns):
id                 888 non-null int64
Task               888 non-null object
Date               888 non-null datetime64[ns]
Module             888 non-null object
Type               888 non-null object
Student            888 non-null object
Late Submission    888 non-null int64
Points             888 non-null float64
Total              888 non-null int64
Task Winner        888 non-null int64
dtypes: datetime64[ns](1), float64(1), int64(4), object(4)
memory usage: 76.3+ KB

In [27]:
np.sort(data_july['Student'].unique())

array(['Anjali', 'Apurwa', 'Arya', 'Bhavna', 'Chandrima', 'Dipam',
       'Durga', 'Kaushal', 'Kunal', 'Prasoon', 'Purbita', 'Roumyak',
       'Shakib', 'Shantanu', 'Sharika', 'Siddhishikha', 'Sonali',
       'Sudhanshu', 'Surabhi', 'Sushree', 'Swaastik', 'Ujjainee',
       'Vishal', 'Wrick'], dtype=object)

In [28]:
np.sort(data_august['Student'].unique())

array(['Anjali', 'Apurwa', 'Arya', 'Bhavna', 'Chandrima', 'Dipam',
       'Durga', 'Kaushal', 'Kunal', 'Nitish', 'Prasoon', 'Purbita',
       'Roumyak', 'Shakib', 'Shantanu', 'Sharika', 'Siddhishikha',
       'Sonali', 'Surabhi', 'Swaastick', 'Swaastik', 'Ujjainee', 'Vishal',
       'Wrick'], dtype=object)

#### Spelling error fixings
From the above 2 rows, we can see that there are different names in the data, Sushree and Siddhishikha is the same person, same for Swaastik and Swaastick.

In [29]:
data_july.replace('Swaastik','Swaastick',inplace=True)
data_august.replace('Swaastik','Swaastick',inplace=True)

In [30]:
data_july.replace('Sushree','Siddhishikha',inplace=True)
data_august.replace('Sushree','Siddhishikha',inplace=True)

In [31]:
np.sort(data_july['Student'].unique())

array(['Anjali', 'Apurwa', 'Arya', 'Bhavna', 'Chandrima', 'Dipam',
       'Durga', 'Kaushal', 'Kunal', 'Prasoon', 'Purbita', 'Roumyak',
       'Shakib', 'Shantanu', 'Sharika', 'Siddhishikha', 'Sonali',
       'Sudhanshu', 'Surabhi', 'Swaastick', 'Ujjainee', 'Vishal', 'Wrick'],
      dtype=object)

In [32]:
np.sort(data_august['Student'].unique())

array(['Anjali', 'Apurwa', 'Arya', 'Bhavna', 'Chandrima', 'Dipam',
       'Durga', 'Kaushal', 'Kunal', 'Nitish', 'Prasoon', 'Purbita',
       'Roumyak', 'Shakib', 'Shantanu', 'Sharika', 'Siddhishikha',
       'Sonali', 'Surabhi', 'Swaastick', 'Ujjainee', 'Vishal', 'Wrick'],
      dtype=object)

The name problem has been resolved.

In [33]:
data_august

,id,Task,Date,Module,Type,Student,Late Submission,Points,Total,Task Winner
0,0,AjKyaUkhada,2019-08-01 13:26:57,Ritual,Consistency,Sonali,0,2.0,2,0
1,0,AjKyaUkhada,2019-08-01 14:40:42,Ritual,Consistency,Chandrima,0,2.0,2,0
2,0,AjKyaUkhada,2019-08-01 14:44:34,Ritual,Consistency,Purbita,0,2.0,2,0
3,0,AjKyaUkhada,2019-08-01 14:47:05,Ritual,Consistency,Kunal,0,2.0,2,0
4,0,AjKyaUkhada,2019-08-01 14:48:11,Ritual,Consistency,Kaushal,0,2.0,2,0
5,0,AjKyaUkhada,2019-08-01 15:05:13,Ritual,Consistency,Durga,0,2.0,2,0
6,0,AjKyaUkhada,2019-08-01 15:55:48,Ritual,Consistency,Ujjainee,0,2.0,2,0
7,0,AjKyaUkhada,2019-08-01 16:08:05,Ritual,Consistency,Dipam,0,2.0,2,0
8,0,AjKyaUkhada,2019-08-01 16:16:30,Ritual,Consistency,Siddhishikha,0,2.0,2,0
9,0,AjKyaUkhada,2019-08-01 16:17:01,Ritual,Consistency,Surabhi,0,2.0,2,0
10,0,AjKyaUkhada,2019-08-01 17:05:15,Ritual,Consistency,Swaastick,0,2.0,2,0
11,0,AjKyaUkhada,2019-08-01 17:29:07,Ritual,Consistency,Sharika,0,2.0,2,0
12,0,AjKyaUkhada,2019-08-01 18:01:53,Ritual,Consistency,Apurwa,0,2.0,2,0
13,0,AjKyaUkhada,2019-08-01 18:21:29,Ritual,Consistency,Shakib,0,2.0,2,0
14,0,AjKyaUkhada,2019-08-01 18:29:24,Ritual,Consistency,Vishal,0,2.0,2,0
15,0,AjKyaUkhada,2019-08-01 19:52:40,Ritual,Consistency,Wrick,0,2.0,2,0
16,5,Video Resume,2019-08-01 00:00:00,Profile Building,"Creativity,Communication,Intent,Confidence",Chandrima,0,16.5,20,0
17,5,Video Resume,2019-08-01 00:00:00,Profile Building,"Creativity,Communication,Intent,Confidence",Dipam,0,14.0,20,0
18,5,Video Resume,2019-08-01 00:00:00,Profile Building,"Creativity,Communication,Intent,Confidence",Durga,0,16.5,20,0
19,5,Video Resume,2019-08-01 00:00:00,Profile Building,"Creativity,Communication,Intent,Confidence",Kaushal,1,16.5,20,0
20,5,Video Resume,2019-08-01 00:00:00,Profile Building,"Creativity,Communication,Intent,Confidence",Arya,1,18.5,20,0
21,5,Video Resume,2019-08-01 00:00:00,Profile Building,"Creativity,Communication,Intent,Confidence",Kunal,0,20.0,20,0
22,5,Video Resume,2019-08-01 00:00:00,Profile Building,"Creativity,Communication,Intent,Confidence",Purbita,0,18.0,20,0
23,5,Video Resume,2019-08-01 00:00:00,Profile Building,"Creativity,Communication,Intent,Confidence",Roumyak,0,20.0,20,1
24,5,Video Resume,2019-08-01 00:00:00,Profile Building,"Creativity,Communication,Intent,Confidence",Shakib,0,17.5,20,0
25,5,Video Resume,2019-08-01 00:00:00,Profile Building,"Creativity,Communication,Intent,Confidence",Shantanu,0,20.0,20,1
26,5,Video Resume,2019-08-01 00:00:00,Profile Building,"Creativity,Communication,Intent,Confidence",Sharika,1,20.0,20,0
27,5,Video Resume,2019-08-01 00:00:00,Profile Building,"Creativity,Communication,Intent,Confidence",Sonali,1,16.5,20,0
28,5,Video Resume,2019-08-01 00:00:00,Profile Building,"Creativity,Communication,Intent,Confidence",Surabhi,0,20.0,20,1
29,5,Video Resume,2019-08-01 00:00:00,Profile Building,"Creativity,Communication,Intent,Confidence",Siddhishikha,0,16.0,20,0
...,...,...,...,...,...,...,...,...,...,...
880,0,AjKyaUkhada,2019-09-08 18:58:19,Ritual,Consistency,Apurwa,0,2.0,2,0
881,0,AjKyaUkhada,2019-09-08 19:13:37,Ritual,Consistency,Bhavna,0,2.0,2,0
882,0,AjKyaUkhada,2019-09-08 19:18:20,Ritual,Consistency,Shantanu,0,2.0,2,0
883,0,AjKyaUkhada,2019-09-09 03:45:18,Ritual,Consistency,Sonali,0,2.0,2,0
884,0,Knowledge Sharing,2019-09-09 04:25:25,Ritual,"Consistency,Curiosity",Dipam,0,2.0,2,0
885,0,AjKyaUkhada,2019-09-09 08:02:49,Ritual,Consistency,Kaushal,0,2.0,2,0
886,0,Knowledge Sharing,2019-09-09 15:56:33,Ritual,"Consistency,Curiosity",Kunal,0,2.0,2,0
887,0,AjKyaUkhada,2019-09-09 16:00:36,Ritual,Consistency,Ujjainee,0,2.0,2,0
888,0,Knowledge Sharing,2019-09-09 16:01:03,Ritual,"Consistency,Curiosity",Surabhi,0,2.0,2,0
889,0,AjKyaUkhada,2019-09-09 16:02:23,Ritual,Consistency,Surabhi,0,2.0,2,0
890,0,Knowledge Sharing,2019-09-09 16:04:59,Ritual,"Consistency,Curiosity",Bhavna,0,2.0,2,0
891,0,AjKyaUkhada,2019-09-09 16:09:54,Ritual,Consistency,Bhavna,0,2.0,2,0
892,0,AjKyaUkhada,2019-09-09 16:30:43,Ritual,Consistency,Purbita,0,2.0,2,0
893,0,AjKyaUkhada,2019-09-09 16:32:51,Ritual,Consistency,Kunal,0,2.0,2,0
894,0,AjKyaUkhada,2019-09-09 16:50:59,Ritual,Consistency,Dipam,0,2.0,2,0
895,0,AjKyaUkhada,2019-09-09 16:54:15,Ritual,Consistency,Durga,0,2.0,2,0
896,0,AjKyaUkhada,2019-09-09 17:07:01,Ritual,Consistency,Chandrima,0,2.0,2,0
897,0,Knowledge Sharing,2019-09-09 17:12:16,Ritual,"Consistency,Curiosity",Kunal,0,2.0,2,0
898,0,AjKyaUkhada,2019-09-09 17:31:12,Ritual,Consistency,Shantanu,0,2.0,2,0
900,0,AjKyaUkhada,2019-09-09 18:15:19,Ritual,Consistency,Shakib,0,2.0,2,0
901,0,AjKyaUkhada,2019-09-09 19:25:21,Ritual,Consistency,Kaushal,0,2.0,2,0
902,0,AjKyaUkhada,2019-09-09 19:27:18,Ritual,Consistency,Vishal,0,2.0,2,0
903,0,AjKyaUkhada,2019-09-09 20:08:02,Ritual,Consistency,Prasoon,0,2.0,2,0
904,0,AjKyaUkhada,2019-09-09 20:08:52,Ritual,Consistency,Prasoon,0,2.0,2,0
905,0,AjKyaUkhada,2019-09-09 20:09:53,Ritual,Consistency,Prasoon,0,2.0,2,0
906,0,AjKyaUkhada,2019-09-09 20:28:38,Ritual,Consistency,Apurwa,0,2.0,2,0
907,0,AjKyaUkhada,2019-09-10 07:28:59,Ritual,Consistency,Sharika,0,2.0,2,0
908,0,Knowledge Sharing,2019-09-10 08:17:51,Ritual,"Consistency,Curiosity",Purbita,0,2.0,2,0
909,0,Knowledge Sharing,2019-09-10 08:24:44,Ritual,"Consistency,Curiosity",Chandrima,0,2.0,2,0
910,0,AjKyaUkhada,2019-09-10 09:20:29,Ritual,Consistency,Swaastick,0,2.0,2,0

In [34]:
marksaug=data_august.groupby('Student')['Points'].sum().sort_values(ascending=False)
marksjuly=data_july.groupby('Student')['Points'].sum().sort_values(ascending=False)
total_marks=(marksjuly+marksaug).sort_values(ascending=False).reset_index().dropna()

In [35]:
total_marks

         Student  Points
0          Kunal   262.5
1        Surabhi   257.5
2       Ujjainee   256.5
3          Dipam   253.5
4        Purbita   250.5
5         Shakib   249.5
6         Vishal   243.5
7      Chandrima   239.0
8         Sonali   238.5
9        Sharika   238.5
10  Siddhishikha   226.0
11        Apurwa   222.5
12         Durga   220.5
13     Swaastick   214.5
14       Kaushal   214.0
15       Prasoon   200.5
16       Roumyak   182.5
17      Shantanu   171.5
18          Arya   161.5
19        Bhavna   122.0
20         Wrick    62.5
21        Anjali    50.0

In [36]:
css = """
<style type=\"text/css\">
table {
color: #333;
font-family: Helvetica, Arial, sans-serif;
width: 640px;
border-collapse:
collapse; 
border-spacing: 0;
}td, th {
border: 1px solid transparent; /* No more visible border */
height: 30px;
}th {
background: #DFDFDF; /* Darken header a bit */
font-weight: bold;
}td {
background: #FAFAFA;
text-align: center;
}table tr:nth-child(odd) td{
background-color: white;
}
</style>
"""

In [37]:
import os

In [38]:
import logging
logger = logging.getLogger('weasyprint')
logger.addHandler(logging.FileHandler('weasyprint.log'))

In [39]:
logger.removeHandler(logging.FileHandler('weasyprint.log'))

In [57]:
total_marks.to_html('tester.html')
with open('tester.html','a') as f:
    f.write(css)
b=weasyprint.CSS(string='@page { size: A4; margin: 0.5cm }')
weasyprint.HTML('tester.html').write_png('t.png',resolution=96,stylesheets=[b])
#os.remove('tester.html')

In [61]:
a=weasyprint.CSS(string='@page { size: A4; margin: 0.2cm; }')
weasyprint.HTML('testing.html').write_pdf('test.pdf',stylesheets=[a],presentational_hints=True)

In [51]:
import pdfkit
pdfkit.from_file('testing.html','test.pdf')

Loading pages (1/6)
Counting pages (2/6)
Resolving links (4/6)
Loading headers and footers (5/6)
Printing pages (6/6)
Done

True

In [43]:
imgkitoptions = {"format": "jpeg"}
imgkit.from_file("tester.html",'t.jpeg', options=imgkitoptions)

Loading page (1/2)
Rendering (2/2)
Done

True

In [44]:
a=total_marks.dropna().style.background_gradient(subset=['Points']).hide_index()

In [45]:
fs=a.render()
with open('test.html','a') as f:
    f.write(fs)
    f.write(css)

In [46]:
imgkit.from_file('test.html','testing.png',options=imgkitoptions)

Loading page (1/2)
Rendering (2/2)
Done

True

In [47]:
mydays=data_august[data_august['Task']=='AjKyaUkhada'].groupby('Student')['Points'].count().sort_values(ascending=False).reset_index()

In [48]:
mydays.style.bar(subset=['Points'],color='#d65f5f')

In [49]:
mydays.style.background_gradient(subset=['Points']).hide_index()